name: Test

on:
  pull_request_target:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Install Dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci

      # - name: Check code style
      #   run: pnpm run lint

      - name: Run Tests
        run: npm run test

  report-coverage:
    runs-on: ubuntu-latest
    needs: test
    if: always() # Also generate the report if tests are failing
    steps:
      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info
          filter-changed-files: true
          delete-old-comments: true
